name: Promote Application
on:
  workflow_dispatch:
    inputs:
      source_env:
        description: 'Source Environment'
        required: true
        default: 'staging'
        type: string
      target_env:
        description: 'Target Environment'
        required: true
        default: 'devex'
        type: string

permissions:
  contents: read

jobs:
  promote:
    name: Promote Application
    runs-on: ubuntu-24.04
    steps:
      - name: Request Promotion
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: thomasvitale/kubecon-eu-2026-gitops
          event-type: app-promotion
          client-payload: |-
            {
              "app_name": "${{ github.event.repository.name }}",
              "source_env": "${{ inputs.source_env }}",
              "target_env": "${{ inputs.target_env }}"
            }
